-- MySQL Script generated by MySQL Workbench
-- Mon Nov  6 08:00:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chat-sweet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chat-sweet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat-sweet` DEFAULT CHARACTER SET utf8 ;
USE `chat-sweet` ;

-- -----------------------------------------------------
-- Table `chat-sweet`.`ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`ingredientes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- Inserta ingredientes en la tabla `ingredientes`
INSERT INTO `chat-sweet`.`ingredientes` (`id`, `name`)
VALUES
  (1, 'Azúcar'),
  (2, 'Harina'),
  (3, 'Mantequilla'),
  (4, 'Huevos'),
  (5, 'Leche'),
  (6, 'Vainilla'),
  (7, 'Chocolate'),
  (8, 'Fresas'),
  (9, 'Crema batida'),
  (10, 'Gelatina'),
  (11, 'Nueces'),
  (12, 'Canela'),
  (13, 'Miel'),
  (14, 'Yogur'),
  (15, 'Galletas');

-- -----------------------------------------------------
-- Table `chat-sweet`.`postres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`postres` (
  `id` INT NOT NULL,
  `receta` LONGTEXT NULL,
  `preparacion` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- Inserta postres en la tabla `postres`
INSERT INTO `chat-sweet`.`postres` (`id`, `receta`, `preparacion`)
VALUES
  (1, 'Pastel de chocolate', '1-Precalienta el horno a 180°C (350°F) y prepara un molde para pastel engrasándolo y enharinándolo.
                            2-En un tazón grande, mezcla la harina, el cacao en polvo, el bicarbonato de sodio y la sal. Reserva esta mezcla seca.
                            3-En otro tazón, bate la mantequilla y el azúcar hasta obtener una mezcla suave y esponjosa.
                            4-Agrega los huevos, uno a la vez, batiendo bien después de cada adición. Luego, mezcla la vainilla.
                            5-Añade la mitad de la mezcla seca a la mezcla húmeda y mezcla bien. Luego, incorpora la mitad de la leche y mezcla nuevamente. Repite este proceso con la otra mitad de la mezcla seca y la leche.
                            6-Agrega el agua caliente a la masa y mezcla hasta obtener una masa homogénea. La masa será líquida, pero esto es normal.
                            7-Vierte la masa en el molde preparado y asegúrate de que esté distribuida de manera pareja.
                            8-Hornea en el horno precalentado durante aproximadamente 30-35 minutos, o hasta que al insertar un palillo en el centro salga limpio.
                            9-Una vez horneado, saca el pastel del horno y déjalo enfriar en el molde durante unos minutos. Luego, transfiérelo a una rejilla para que se enfríe por completo.
                            10-Una vez que el pastel esté completamente frío, puedes decorarlo con ganache de chocolate, crema batida, fresas u otros ingredientes a tu gusto.'),
  
  (2, 'Galletas de vainilla', '1-En un tazón grande, mezcla la harina, el polvo de hornear y la sal. Reserva esta mezcla seca.
                            2-En otro tazón, bate la mantequilla y el azúcar hasta obtener una mezcla suave y esponjosa.
                            3-Agrega el huevo y la vainilla a la mezcla de mantequilla y azúcar. Mezcla hasta que estén bien combinados.
                            4-Añade gradualmente la mezcla seca a la mezcla húmeda. Mezcla hasta obtener una masa uniforme y suave.
                            5-Envuelve la masa en papel film y refrigérala durante al menos 1 hora. Esto ayudará a que la masa se endurezca y sea más fácil de manejar.
                            6-Precalienta el horno a 180°C (350°F) y prepara bandejas para hornear cubriéndolas con papel encerado o con un tapete de silicona.
                            7-Retira la masa del refrigerador y forma pequeñas bolitas del tamaño de una nuez.
                            8-Coloca las bolitas de masa en las bandejas para hornear, dejando un espacio entre cada una, ya que se expandirán durante la cocción.
                            9-Con el dorso de un tenedor, aplasta ligeramente cada galleta para darle forma.
                            10-Hornea las galletas en el horno precalentado durante aproximadamente 10-12 minutos, o hasta que estén doradas en los bordes.
                            11-Retira las bandejas del horno y deja enfriar las galletas durante unos minutos antes de transferirlas a una rejilla para que se enfríen por completo.'),
  
  (3, 'Flan de leche', '1-En una olla pequeña, calienta el azúcar a fuego medio-bajo hasta que se derrita y se caramelice. Remueve constantemente para evitar que se queme. Una vez que el azúcar esté completamente derretido y tenga un color dorado, retira del fuego y viértelo rápidamente en el fondo de los moldes individuales para flan. Deja que el caramelo se endurezca.
                        2-En una cacerola mediana, calienta la leche a fuego medio-alto hasta que alcance el punto de ebullición. Luego, retírala del fuego y déjala enfriar ligeramente.  
                        3-En un tazón aparte, bate los huevos y las yemas hasta que estén bien batidos y mezclados.
                        4-Añade el azúcar, la esencia de vainilla y la sal a los huevos batidos. Mezcla bien hasta que el azúcar se disuelva por completo.
                        5-Añade gradualmente la leche caliente a la mezcla de huevo, vertiéndola lentamente mientras bates constantemente. Asegúrate de mezclar bien para evitar que los huevos se cuajen.
                        6-Vierte la mezcla de flan en los moldes individuales sobre el caramelo endurecido. Llena cada molde hasta aproximadamente 3/4 de su capacidad.
                        7-Prepara un baño de agua caliente para hornear los flanes. Coloca los moldes individuales dentro de una fuente para horno más grande y vierte agua caliente en la fuente hasta que llegue aproximadamente a la mitad de la altura de los moldes.
                        8-Coloca la fuente en el horno precalentado a 180°C (350°F) y hornea durante aproximadamente 40-45 minutos, o hasta que los flanes estén firmes pero todavía temblorosos en el centro.
                        9-Retira los moldes del baño de agua caliente y déjalos enfriar a temperatura ambiente durante unos minutos. Luego, refrigera los flanes durante al menos 2 horas, o preferiblemente durante la noche, para que se enfríen y cuajen por completo.
                        10-Para servir, desmolda los flanes pasando un cuchillo por los bordes y luego dándoles la vuelta sobre un plato. El caramelo líquido se verterá sobre los flanes. Disfruta de tu delicioso flan de leche bien frío.'),
  
  (4, 'Tarta de fresas', '1. Prepara la base de la tarta. Puedes usar una base de galletas trituradas mezcladas con mantequilla derretida o una base de masa quebrada. 
                                a. Si optas por la base de galletas, tritura las galletas en un procesador de alimentos o colócalas en una bolsa y aplástalas con un rodillo hasta que estén bien trituradas. Luego, mezcla las galletas trituradas con mantequilla derretida hasta obtener una textura arenosa.
                                b. Si prefieres la base de masa quebrada, extiende la masa sobre un molde para tarta previamente engrasado y pincha el fondo con un tenedor. Luego, hornea la base de masa quebrada siguiendo las instrucciones del paquete.
                            2. Hornea la base de la tarta según las indicaciones de la receta o hasta que esté dorada y crujiente. Deja enfriar completamente.
                            3. Prepara la crema pastelera. Para ello, mezcla en una cacerola la leche, el azúcar, la harina de maíz, las yemas de huevo y la vainilla. Cocina a fuego medio-bajo, removiendo constantemente, hasta que la mezcla espese y hierva. Retira del fuego y deja enfriar.
                            4. Una vez que la crema pastelera esté fría, extiéndela sobre la base de la tarta enfriada.
                            5. Lava y corta las fresas en rodajas. Coloca las rodajas de fresa sobre la crema pastelera de manera decorativa, cubriendo toda la superficie de la tarta.
                            6. Opcionalmente, puedes hacer un glaseado para darle brillo a las fresas. Para ello, calienta gelatina o mermelada de fresa en una cacerola pequeña hasta que se derrita. Luego, pincela suavemente las fresas con el glaseado.
                            7. Refrigera la tarta durante al menos una hora para que se enfríe y asiente.
                            8. Sirve y disfruta de tu deliciosa tarta de fresas. Puedes acompañarla con una bola de helado de vainilla o crema batida si lo deseas.'),
  
  (5, 'Helado de vainilla', '1. En una cacerola mediana, calienta la leche y la crema a fuego medio hasta que comience a hervir. Retira del fuego y reserva.
                            2. En un tazón aparte, bate las yemas de huevo y el azúcar hasta que estén bien combinados y la mezcla esté suave y ligeramente espesa.
                            3. Vierte lentamente la mezcla de leche caliente sobre las yemas batidas, revolviendo constantemente para evitar que los huevos se cuajen.
                            4. Vuelve a colocar la mezcla en la cacerola y caliéntala a fuego medio-bajo, revolviendo constantemente con una cuchara de madera. Cocina la mezcla hasta que espese lo suficiente para cubrir el dorso de la cuchara (alrededor de 5-7 minutos). No dejes que la mezcla hierva.
                            5. Retira la cacerola del fuego y añade la vainilla. Revuelve bien para incorporarla.
                            6. Coloca la mezcla en un recipiente hermético y refrigera durante al menos 4 horas o hasta que esté completamente fría.
                            7. Una vez que la mezcla esté fría, transfiérela a la máquina para hacer helados siguiendo las instrucciones del fabricante. Generalmente, se necesita aproximadamente de 20 a 30 minutos para obtener la consistencia deseada.
                            8. Si quieres agregar algún ingrediente adicional, como trozos de chocolate o nueces, agrégalos durante los últimos minutos del proceso de preparación del helado.
                            9. Transfiere el helado recién hecho a un recipiente hermético y congélalo durante al menos 2-4 horas para que adquiera una textura firme.
                            10. ¡Disfruta de tu helado de vainilla casero! Puedes servirlo solo, con siropes o con tus toppings favoritos. '),
  
  (6, 'Brownies de nueces', '1. Precalienta el horno a 180°C (350°F) y prepara un molde cuadrado o rectangular engrasándolo o cubriéndolo con papel de hornear.
                            2. En un tazón grande, derrite la mantequilla y el chocolate en el microondas o a baño maría. Remueve hasta que estén completamente derretidos y mezclados.
                            3. Agrega el azúcar y el azúcar moreno a la mezcla de chocolate derretido y mantequilla. Mezcla bien hasta que estén combinados.
                            4. Añade los huevos uno a uno, batiendo bien después de cada adición.
                            5. Agrega la esencia de vainilla y mezcla nuevamente.
                            6. Tamiza la harina, el cacao en polvo y la sal en la mezcla de chocolate. Mezcla todo hasta que esté bien combinado y no queden grumos de harina.
                            7. Agrega las nueces picadas a la masa del brownie y mezcla suavemente.
                            8. Vierte la masa en el molde preparado y extiéndela de manera uniforme.
                            9. Hornea en el horno precalentado durante unos 25-30 minutos, o hasta que un palillo insertado en el centro salga con algunas migas pegadas pero no líquido. No cocines en exceso para evitar que los brownies se sequen.
                            10. Una vez horneados, retira los brownies del horno y deja que se enfríen por completo en el molde antes de cortarlos en cuadrados.
                            11. Si lo deseas, puedes espolvorear un poco de azúcar glas o cocoa en polvo sobre los brownies antes de servir.'),
  
  (7, 'Bizcocho de miel', '1. Precalienta el horno a 180°C (350°F) y engrasa un molde para bizcocho con mantequilla o aceite.
                            2. En un tazón grande, mezcla la harina, el bicarbonato de sodio y la sal. Reserva.
                            3. En otro tazón, bate la mantequilla ablandada y el azúcar hasta obtener una mezcla suave y cremosa.
                            4. Añade los huevos uno a uno, batiendo bien después de cada adición. Agrega la miel y la esencia de vainilla y mezcla hasta que esté todo bien combinado.
                            5. Incorpora la mitad de la mezcla de harina a la mezcla de mantequilla y huevos, y luego añade la mitad de la leche. Mezcla bien. Repite este paso con la otra mitad de la harina y la leche, asegurándote de mezclar hasta obtener una masa homogénea.
                            6. Vierte la masa en el molde preparado y alisa la superficie con una espátula.
                            7. Hornea el bizcocho en el horno precalentado durante aproximadamente 30-35 minutos, o hasta que al insertar un palillo en el centro, este salga limpio.
                            8. Una vez que esté listo, retira el bizcocho del horno y deja que se enfríe en el molde durante unos minutos antes de desmoldarlo sobre una rejilla de enfriamiento.
                            9. Para decorar, puedes espolvorear azúcar glas por encima o cubrirlo con un glaseado de miel.
                            10. Una vez que el bizcocho esté completamente frío, córtalo en rebanadas y sírvelo. ¡Disfruta de tu delicioso bizcocho de miel! '),
  
  (8, 'Yogur con fresas', '1. Lava y corta las fresas en trozos pequeños. Puedes ajustar la cantidad de fresas según tus preferencias.
                            2. En una licuadora o procesadora de alimentos, agrega las fresas troceadas y tritúralas hasta obtener un puré suave.
                            3. En un recipiente grande, mezcla el puré de fresas con el yogur natural. Añade azúcar o cualquier otro endulzante a tu gusto, si lo deseas.
                            4. Mezcla bien para que las fresas se incorporen por completo al yogur.
                            5. Si tienes una máquina para hacer helado o yogur, sigue las instrucciones del fabricante para congelar la mezcla. Si no tienes una máquina, puedes verter la mezcla en recipientes individuales adecuados para congelar.
                            6. Coloca los recipientes en el congelador y déjalos allí durante al menos 4 horas, o hasta que el yogur esté completamente congelado.
                            7. Una vez que el yogur esté congelado, retíralo del congelador y déjalo reposar a temperatura ambiente durante unos minutos para que se ablande ligeramente antes de servir.
                            8. Sirve el yogur con fresas en tazones individuales y, si lo deseas, decora con rodajas frescas de fresa o cualquier otro ingrediente adicional que te guste. '),
  
  (9, 'Tarta de crema batida', '1. Prepara la base de la tarta. Puedes usar una base de galletas trituradas mezcladas con mantequilla derretida o una base de masa quebrada. 
                                    - Si optas por la base de galletas, tritura las galletas en un procesador de alimentos o colócalas en una bolsa y aplástalas con un rodillo hasta que estén bien trituradas. Luego, mezcla las galletas trituradas con mantequilla derretida hasta obtener una textura arenosa.
                                    - Si prefieres la base de masa quebrada, extiende la masa sobre un molde para tarta previamente engrasado y pincha el fondo con un tenedor. Luego, hornea la base de masa quebrada según las instrucciones del paquete.
                                2. Hornea la base de la tarta según las indicaciones de la receta o hasta que esté dorada y crujiente. Deja enfriar completamente.
                                3. Prepara la crema batida. Para ello, bate la crema para batir en un tazón grande hasta que comience a espesarse. Agrega el azúcar y la vainilla y continúa batiendo hasta obtener una consistencia firme y picos suaves.
                                4. Una vez que la base de la tarta esté fría, extiende la crema batida sobre ella de manera uniforme.
                                5. Opcionalmente, puedes agregar frutas frescas como fresas o frambuesas encima de la crema batida para decorar y darle un toque adicional de sabor.
                                6. Refrigera la tarta durante al menos una hora para que se enfríe y asiente. Esto ayudará a que la crema batida se mantenga firme y la tarta adquiera mejor sabor.
                                7. Sirve y disfruta de tu deliciosa tarta de crema batida. Puedes decorarla con más frutas frescas, chocolate rallado o cualquier otro topping de tu elección. '),
  
  (10, 'Gelatina de sabores', '1. Reúne los ingredientes necesarios. Necesitarás paquetes de gelatina en los sabores que desees, azúcar (opcional) y agua caliente.
                                2. Sigue las instrucciones del paquete de gelatina para cada sabor específico. En general, deberás disolver un paquete de gelatina en polvo en una taza de agua caliente. Algunas variedades pueden requerir más o menos agua, así que verifica las instrucciones del paquete.
                                3. Si deseas que la gelatina sea más dulce, puedes agregar azúcar al polvo de gelatina antes de mezclarlo con agua caliente. La cantidad de azúcar a añadir dependerá de tus preferencias personales.
                                4. Revuelve bien la gelatina en polvo y el agua caliente hasta que se disuelva por completo.
                                5. Luego, agrega una taza de agua fría a la mezcla de gelatina y revuelve nuevamente. Esto ayudará a enfriar la mezcla y lograr la consistencia de gelatina.
                                6. Continúa preparando gelatinas de diferentes sabores siguiendo los pasos anteriores. Puedes usar diferentes colores y sabores para obtener una variedad de gelatinas.
                                7. Vierte la gelatina líquida en moldes individuales o en un molde grande según tu preferencia. Puedes usar moldes de silicona, moldes para flan o cualquier recipiente adecuado.
                                8. Coloca la gelatina en el refrigerador y déjala enfriar durante al menos 3-4 horas, o hasta que esté completamente cuajada.
                                9. Una vez que la gelatina esté cuajada, puedes desmoldarla si usaste moldes individuales. Para ello, sumerge rápidamente el molde en agua caliente para aflojar los bordes, luego coloca un plato sobre el molde y dale la vuelta para que la gelatina se desprenda.
                                10. Sirve la gelatina de sabores como postre o como parte de una fiesta. Puedes decorarla con crema batida, frutas frescas o cualquier otro acompañamiento de tu elección.');

-- -----------------------------------------------------
-- Table `chat-sweet`.`ingredientes_has_postres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`ingredientes_has_postres` (
  `ingredientes_id` INT NOT NULL,
  `postres_id` INT NOT NULL,
  PRIMARY KEY (`ingredientes_id`, `postres_id`),
  INDEX `fk_ingredientes_has_postres_postres1_idx` (`postres_id` ASC) VISIBLE,
  INDEX `fk_ingredientes_has_postres_ingredientes_idx` (`ingredientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredientes_has_postres_ingredientes`
    FOREIGN KEY (`ingredientes_id`)
    REFERENCES `chat-sweet`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredientes_has_postres_postres1`
    FOREIGN KEY (`postres_id`)
    REFERENCES `chat-sweet`.`postres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Inserta en la tabla pivote `ingredientes_has_postres`
INSERT INTO `chat-sweet`.`ingredientes_has_postres` (`ingredientes_id`, `postres_id`)
VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 1),
  (2, 3),
  (3, 1),
  (3, 2),
  (3, 3),
  (4, 1),
  (5, 1),
  (5, 2),
  (6, 2),
  (7, 1),
  (8, 2),
  (8, 3),
  (9, 2),
  (9, 3),
  (10, 2),
  (11, 2),
  (11, 3),
  (12, 3),
  (13, 3),
  (14, 2),
  (15, 3);

-- -----------------------------------------------------
-- Table `chat-sweet`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`person` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat-sweet`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `chat-sweet`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat-sweet`.`chatbot_no_replies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`chatbot_no_replies` (
  `id` INT NOT NULL,
  `queries_no_replies` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatbot_no_replies_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_chatbot_no_replies_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `chat-sweet`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat-sweet`.`chatbot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat-sweet`.`chatbot` (
  `id` INT NOT NULL,
  `queries` VARCHAR(45) NULL,
  `replies` VARCHAR(45) NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chatbot_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_chatbot_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `chat-sweet`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
